name: Build

on: [workflow_call]

jobs:
  build:
    runs-on: ubuntu-latest
    # Include multiple dockerfiles and names in the matrix to build and push multiple images
    # All these images need to be pulled with docker compose during deployment
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./Dockerfile
            image: ghcr.io/dy0gu/firewatcher
            secret-id: BOT_TOKEN
            secret-value: BOT_TOKEN
    # Sets the permissions granted to the GITHUB_TOKEN for the actions in this job
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      # Once published, the packages are scoped to the account defined here
      - name: Log in to the container registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: dy0gu
          password: ${{ secrets.GITHUB_TOKEN }}
      # Extract tags and labels that will be applied to the specified image.
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ matrix.image }}
      # The "tags" and "labels" parameters of the build are acquired from the output of the meta step.
      - name: Build and push Docker image
        uses: docker/build-push-action@v5.2.0
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          secrets: "${{ matrix.secret-id }}=${{ secrets[matrix.secret-value] }}"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
