name: Deploy

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    environment:
      name: Production
      url: https://discord.com/oauth2/authorize?client_id=999712607227359274&permissions=0&scope=bot
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd ~
            sudo NEEDRESTART_MODE=a apt-get update -y
            sudo NEEDRESTART_MODE=a apt-get upgrade -y
            sudo NEEDRESTART_MODE=a apt-get autoremove -y
            sudo NEEDRESTART_MODE=a apt-get autoclean -y
            sudo NEEDRESTART_MODE=a apt-get install neovim -y
            sudo NEEDRESTART_MODE=a apt-get install tmux -y
            sudo NEEDRESTART_MODE=a apt-get install git -y
            sudo NEEDRESTART_MODE=a apt-get install python3 -y
            sudo NEEDRESTART_MODE=a apt-get install python3-pip -y
            tmux kill-server
            rm -rf *
            git clone -b prod --single-branch ${{ github.server_url }}/${{ github.repository }}.git Repository
            cd Repository
            pip3 install -r requirements.txt
            echo 'BOT_TOKEN="${{ secrets.TOKEN }}"' > .env
            tmux new -d -s deployment
            tmux split-window -h -t deployment:0.0
            tmux send-keys -t deployment:0.0 "python3 app/bot.py" Enter
            tmux send-keys -t deployment:0.1 "htop" Enter
